ALTER TABLE about_page
  ADD COLUMN brand1 VARCHAR(500) DEFAULT NULL AFTER video_url,
  ADD COLUMN brand2 VARCHAR(500) DEFAULT NULL AFTER brand1,
  ADD COLUMN brand3 VARCHAR(500) DEFAULT NULL AFTER brand2,
  ADD COLUMN brand4 VARCHAR(500) DEFAULT NULL AFTER brand3,
  ADD COLUMN brand5 VARCHAR(500) DEFAULT NULL AFTER brand4,
  ADD COLUMN brand6 VARCHAR(500) DEFAULT NULL AFTER brand5,
  ADD COLUMN brand7 VARCHAR(500) DEFAULT NULL AFTER brand6,
  ADD COLUMN brand8 VARCHAR(500) DEFAULT NULL AFTER brand7,
  ADD COLUMN brand9 VARCHAR(500) DEFAULT NULL AFTER brand8,
  ADD COLUMN brand10 VARCHAR(500) DEFAULT NULL AFTER brand9;
