export const PAYMENT_METHODS = {
  cod: {
    id: "cod",
    labelKey: "payment.cashOnDelivery",
    descriptionKey: "payment.codDesc",
    icon: "💵",
    type: "offline",
  },
  card: {
    id: "card",
    labelKey: "payment.creditDebitCard",
    descriptionKey: "payment.cardDesc",
    icon: "💳",
    type: "online",
  },
  paypal: {
    id: "paypal",
    labelKey: "payment.paypal",
    descriptionKey: "payment.paypalDesc",
    icon: "🅿️",
    type: "online",
  },
  bank_transfer: {
    id: "bank_transfer",
    labelKey: "payment.bankTransfer",
    descriptionKey: "payment.bankTransferDesc",
    icon: "🏦",
    type: "offline",
  },
  upi: {
    id: "upi",
    labelKey: "payment.upi",
    descriptionKey: "payment.upiDesc",
    icon: "📱",
    type: "online",
  },
  net_banking: {
    id: "net_banking",
    labelKey: "payment.netBanking",
    descriptionKey: "payment.netBankingDesc",
    icon: "🏦",
    type: "online",
  },
  razorpay: {
    id: "razorpay",
    labelKey: "payment.razorpay",
    descriptionKey: "payment.razorpayDesc",
    icon: "🔵",
    type: "online",
  },
  apple_pay: {
    id: "apple_pay",
    labelKey: "payment.applePay",
    descriptionKey: "payment.applePayDesc",
    icon: "",
    type: "online",
  },
  google_pay: {
    id: "google_pay",
    labelKey: "payment.googlePay",
    descriptionKey: "payment.googlePayDesc",
    icon: "🔵",
    type: "online",
  },
  klarna: {
    id: "klarna",
    labelKey: "payment.klarna",
    descriptionKey: "payment.klarnaDesc",
    icon: "🟠",
    type: "online",
  },
  ideal: {
    id: "ideal",
    labelKey: "payment.ideal",
    descriptionKey: "payment.idealDesc",
    icon: "🔷",
    type: "online",
  },
  sepa: {
    id: "sepa",
    labelKey: "payment.sepa",
    descriptionKey: "payment.sepaDesc",
    icon: "🏦",
    type: "online",
  },
  bancontact: {
    id: "bancontact",
    labelKey: "payment.bancontact",
    descriptionKey: "payment.bancontactDesc",
    icon: "🟡",
    type: "online",
  },
  giropay: {
    id: "giropay",
    labelKey: "payment.giropay",
    descriptionKey: "payment.giropayDesc",
    icon: "🔴",
    type: "online",
  },
  swish: {
    id: "swish",
    labelKey: "payment.swish",
    descriptionKey: "payment.swishDesc",
    icon: "🟣",
    type: "online",
  },
  bkash: {
    id: "bkash",
    labelKey: "payment.bkash",
    descriptionKey: "payment.bkashDesc",
    icon: "🟠",
    type: "online",
  },
  nagad: {
    id: "nagad",
    labelKey: "payment.nagad",
    descriptionKey: "payment.nagadDesc",
    icon: "🔴",
    type: "online",
  },
  promptpay: {
    id: "promptpay",
    labelKey: "payment.promptpay",
    descriptionKey: "payment.promptpayDesc",
    icon: "🟢",
    type: "online",
  },
  truemoney: {
    id: "truemoney",
    labelKey: "payment.truemoney",
    descriptionKey: "payment.truemoneyDesc",
    icon: "🟣",
    type: "online",
  },
  gopay: {
    id: "gopay",
    labelKey: "payment.gopay",
    descriptionKey: "payment.gopayDesc",
    icon: "🟢",
    type: "online",
  },
  ovo: {
    id: "ovo",
    labelKey: "payment.ovo",
    descriptionKey: "payment.ovoDesc",
    icon: "🟣",
    type: "online",
  },
  dana: {
    id: "dana",
    labelKey: "payment.dana",
    descriptionKey: "payment.danaDesc",
    icon: "🔵",
    type: "online",
  },
  alipay: {
    id: "alipay",
    labelKey: "payment.alipay",
    descriptionKey: "payment.alipayDesc",
    icon: "🔵",
    type: "online",
  },
  wechat_pay: {
    id: "wechat_pay",
    labelKey: "payment.wechatPay",
    descriptionKey: "payment.wechatPayDesc",
    icon: "🟢",
    type: "online",
  },
  konbini: {
    id: "konbini",
    labelKey: "payment.konbini",
    descriptionKey: "payment.konbiniDesc",
    icon: "🏪",
    type: "offline",
  },
  pix: {
    id: "pix",
    labelKey: "payment.pix",
    descriptionKey: "payment.pixDesc",
    icon: "🟢",
    type: "online",
  },
  boleto: {
    id: "boleto",
    labelKey: "payment.boleto",
    descriptionKey: "payment.boletoDesc",
    icon: "📄",
    type: "offline",
  },
  tabby: {
    id: "tabby",
    labelKey: "payment.tabby",
    descriptionKey: "payment.tabbyDesc",
    icon: "🟣",
    type: "online",
  },
  tamara: {
    id: "tamara",
    labelKey: "payment.tamara",
    descriptionKey: "payment.tamaraDesc",
    icon: "🟢",
    type: "online",
  },
  grabpay: {
    id: "grabpay",
    labelKey: "payment.grabpay",
    descriptionKey: "payment.grabpayDesc",
    icon: "🟢",
    type: "online",
  },
};

const REGION_MAP = {
  IN: ["upi", "razorpay", "net_banking", "card", "cod"],
  US: ["card", "paypal", "apple_pay", "google_pay"],
  CA: ["card", "paypal", "apple_pay", "google_pay"],
  GB: ["card", "paypal", "klarna", "apple_pay", "google_pay"],
  AU: ["card", "paypal", "apple_pay", "google_pay"],
  NZ: ["card", "paypal", "apple_pay"],
  DE: ["card", "paypal", "klarna", "sepa", "giropay"],
  FR: ["card", "paypal", "klarna", "sepa", "apple_pay"],
  NL: ["card", "paypal", "ideal", "klarna", "sepa"],
  BE: ["card", "paypal", "bancontact", "klarna", "sepa"],
  IT: ["card", "paypal", "klarna", "sepa", "apple_pay"],
  ES: ["card", "paypal", "klarna", "sepa", "apple_pay"],
  AT: ["card", "paypal", "klarna", "sepa"],
  SE: ["card", "paypal", "klarna", "swish"],
  NO: ["card", "paypal", "klarna", "vipps"],
  DK: ["card", "paypal", "klarna", "mobilepay"],
  FI: ["card", "paypal", "klarna"],
  PT: ["card", "paypal", "klarna", "sepa", "mbway"],
  IE: ["card", "paypal", "klarna", "apple_pay"],
  CH: ["card", "paypal", "twint"],
  PL: ["card", "paypal", "blik", "przelewy24", "sepa"],
  CZ: ["card", "paypal", "klarna", "sepa"],
  RO: ["card", "paypal", "sepa"],
  JP: ["card", "konbini", "paypal", "apple_pay"],
  CN: ["card", "alipay", "wechat_pay"],
  BR: ["card", "pix", "boleto", "paypal"],
  BD: ["card", "bkash", "nagad", "cod"],
  TH: ["card", "promptpay", "truemoney", "cod", "grabpay"],
  ID: ["card", "gopay", "ovo", "dana", "cod"],
  MY: ["card", "grabpay", "touchngo", "cod"],
  SG: ["card", "paypal", "grabpay"],
  PH: ["card", "grabpay", "gcash", "cod"],
  VN: ["card", "cod", "momo"],
  AE: ["card", "paypal", "tabby", "tamara", "cod"],
  SA: ["card", "tabby", "tamara", "cod"],
  QA: ["card", "cod", "tabby"],
  KW: ["card", "cod", "tabby"],
  BH: ["card", "cod"],
  OM: ["card", "cod"],
  PK: ["card", "cod", "jazzcash", "easypaisa"],
  LK: ["card", "cod"],
  NP: ["card", "cod", "esewa"],
  EG: ["card", "cod", "fawry"],
  ZA: ["card", "paypal", "snapscan"],
  NG: ["card", "cod", "paystack"],
  KE: ["card", "mpesa", "cod"],
  MX: ["card", "paypal", "oxxo"],
  AR: ["card", "paypal", "mercadopago"],
  CL: ["card", "paypal", "webpay"],
  CO: ["card", "pse", "cod"],
  PE: ["card", "plin", "yape"],
};

export const COUNTRY_PAYMENTS = {
  default: ["card", "paypal", "cod"],
  ...REGION_MAP,
};

export function getPaymentMethods(iso2) {
  const code = (iso2 || "IN").toUpperCase();
  const methodIds = COUNTRY_PAYMENTS[code] || COUNTRY_PAYMENTS.default;
  return methodIds.map((id) => PAYMENT_METHODS[id]).filter(Boolean);
}
